### ISSUE TITLE
Gaps between blocks

### ISSUE THREAD

**Issue by Daniel-Bullock** [carl-vbn/minecraft-voxel-loader#2]
I saw a previous issue saying to solve gaps between blocks to use a subsurface modifier but I'm still getting gaps between blocks I'm not sure if this is an issue with the model I have or something. This is what I've been using. I have downloaded a model off the internet and then increased the scale idk if that would effect things. Thanks for this awesome mod though!
![image](https://user-images.githubusercontent.com/47284727/131285845-a8d3e220-4b40-4c4d-b7bf-ac282aa01bee.png)

**Comment by carl-vbn** [comment]
The script that converts the model to voxels only uses the vertices of the mesh. Therefore, if there is too much space between two vertices, no blocks will be placed there. The subsurf modifier works well if your mesh has uniform detail, meaning that the vertex density is roughly the same everywhere. If you have some large faces, consider subdiving them manually or adding some loop cuts. Once the detail is uniform everywhere you can increase the subsurf modifier level until there are no more gaps.
I hope this makes things more clear!

**Comment by Daniel-Bullock** [comment]
Thank you this worked! I have one other issue and that is that conduits are used in the ingame structure a good amount, and always spawn in water, which then drips down the build. Do you know of a way so that certain blocks can not not be spawned in with the commands?

**Comment by carl-vbn** [comment]
Sadly, that is still an issue I haven't addressed. Currently, the only way to blacklist certain blocks is to edit the mod's code. If you are able to do that and rebuild the mod afterwards, the line you have to edit is [line 71 inside VoxelLoader.java](https://github.com/carl-vbn/minecraft-voxel-loader/blob/main/src/main/java/carlvbn/vxloader/VoxelLoader.java#L71), where you can add a check to make sure the block isn't a conduit. 
The other solution, which is easier if you are using vertex colors, is to change the color that is producing conduits by a little bit so that it produces another block instead, but that could be annoying if you are using a texture. 
If you are unable to fix it by yourself, I will soon start working on an update to prevent such problems more easily.

**Comment by Daniel-Bullock** [comment]
Thanks for the help! I'll try editing that line.
