### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Scorious** [carl-vbn/minecraft-voxel-loader#3]
Hi Carl,

Beforehand I want to say that I am extremely excited about this Minecraft animation tutorial you created. I am a designer myself and have a bit of experience with 3D animation. I am struggling to get everything to work.

It says permission denied, how can I fix this? Is it okay if we can voicechat on discord, since I have a few more questions. 

Thank you so much for your future help, I am really bad at this type of stuff. 

_Scorious_

![2021-09-07 (7)](https://user-images.githubusercontent.com/90284611/132413760-4285d0fa-a80d-4c92-a8f4-4de94ab4b8fc.png)

**Comment by Scorious** [comment]
Oops, I went through the closed issues and figured out I forgot to save it. I'm going to experiment tomorrow. The other problem I had was that I did not know how to extract the assets into the color extractor script. 

I know you said in your previous issue you don't have any donation system, maybe make a patreon. I will for sure subscribe. 

SO excited to make Minecraft animations. Got to sleep now, bye! 

_Scorious_

**Comment by carl-vbn** [comment]
Glad to hear you fixed the problem. The script is programmed to automatically save the file when you press the "Voxelize" button in case something crashes but I haven't added a check to see if the project is actually bound to a file. I am currently working on an improved version of the script so I might add it. Let me know if you encounter any further issues, otherwise you can close the issue.
If you really want to support me, sharing the channel with people who might be interested is definitely the best way. At the moment I really don't feel comfortable setting up a Patreon considering my messy upload schedule, but maybe in the future if I ever get used to making videos more regularly.

**Comment by Scorious** [comment]
Thanks, Carl. I am going to experiment a lot. I'll let you know if I get any other problems.
